name: Cache Demo Workflow

on:
  push:
    branches:
      - main  # or your default branch

jobs:
  cache-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step to prime cache
      - name: prime-cache-14d3547
        id: cache-step
        uses: actions/cache@v4
        with:
          path: ~/.npm  # Example: caching npm dependencies
          key: cache-14d3547

      # Step to echo cache hit/miss
      - name: Show cache result
        run: |
          if [ -n "${{ steps.cache-step.outputs.cache-hit }}" ]; then
            echo "Cache hit!"
          else
            echo "Cache miss!"
          fi
