name: IITM Action Test

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: 24f2005506@ds.study.iitm.ac.in
        run: echo "Hello, world!"
